#!/bin/bash
set -x
builtimage=quay.io/$USER/ope-base:stable
opfimage=quay.io/jappavoo/bu-cs-book-dev:latest

v=$1
if [[ -n $v ]]; then
  v=_${v}
fi

docker tag $builtimage quay.io/jappavoo/bu-cs-book-dev:ope_stable${v}
docker push quay.io/jappavoo/bu-cs-book-dev:ope_stable${v}
docker tag quay.io/jappavoo/bu-cs-book-dev:ope_stable${v} ${opfimage}
docker push $opfimage
