#!/bin/bash
# this is our crude bash script to try and find all python functions
# in all the .py files within a directory tree

#set -n  # -n dry run  good for syntax checking (without running any commands)
#set -x  # tracing of simple commands on 
#set -e  # exit script on any fail return code
#set -u  # error if expanding unset variable ... goood for catching typeos

DIR=$1
[[ -z $DIR ]] && echo "USAGE: $0 <directory>" && exit -1

find $DIR -name "*.py" | while read file
do
    cat -n $file | grep 'def '| while read line def func rest; do
	func=${func%%(*}
	echo $func $file: $line
    done	
done | sort 
