#!/bin/bash

VERSIONS=base/private_mamba_versions.stable

echo $(while read pkg; do
   info=$(grep "^${pkg}" $VERSIONS)
   if [[ -n $info ]]; then	   
     echo "$info" | while read pkg ver rest; do
       echo "${pkg}=$ver"
     done
   else
       echo "${pkg}"
   fi
done)
